In [21]:
import cv2
import numpy as np
from numpy import pi, exp, sqrt
import matplotlib.pyplot as plt
%matplotlib inline


In [26]:
# img = cv2.imread('puppy.jpg', 0)
# im = np.array(img, dtype=float)
# plt.show(img)
# # plt.imshow(im)

# im = np.array(Image.open('kitty.jpg'),dtype= int)
# print(im.shape)



img = cv2.imread("kitty.jpg", 0)
im = np.array(img, dtype=float)
type(im)
print(im)


numpy.ndarray

In [29]:
guassian_mask = np.array([[1,1,2,2,2,1,1],[1,2,2,4,2,2,1],[2,2,4,8,4,2,2],[2,4,8,16,8,4,2],[2,2,4,8,4,2,2],[1,2,2,4,2,2,1],[1,1,2,2,2,1,1]])
print(guassian_mask)



[[ 1  1  2  2  2  1  1]
 [ 1  2  2  4  2  2  1]
 [ 2  2  4  8  4  2  2]
 [ 2  4  8 16  8  4  2]
 [ 2  2  4  8  4  2  2]
 [ 1  2  2  4  2  2  1]
 [ 1  1  2  2  2  1  1]]


In [ ]:
height = img.shape[0]
width = img.shape[1]

gauss = (1.0/57) * np.array(
        [[0, 1, 2, 1, 0],
        [1, 3, 5, 3, 1],
        [2, 5, 9, 5, 2],
        [1, 3, 5, 3, 1],
        [0, 1, 2, 1, 0]])
sum(sum(gauss))

for i in np.arange(2, height-2):
    for j in np.arange(2, width-2):        
        sum = 0
        for k in np.arange(-2, 3):
            for l in np.arange(-2, 3):
                a = img.item(i+k, j+l)
                p = gauss[2+k, 2+l]
                sum = sum + (p * a)
        b = sum
        img_out.itemset((i,j), b)

cv2.imwrite('images/filter_gauss.jpg', img_out)

cv2.imshow('image',img_out)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
s, k = 1, 2 #  generate a (2k+1)x(2k+1) gaussian kernel with mean=0 and sigma = s
probs = [exp(-z*z/(2*s*s))/sqrt(2*pi*s*s) for z in range(-k,k+1)] 
kernel = np.outer(probs, probs)
print(kernel)

plt.imshow(kernel)
plt.colorbar()
plt.show()